### ISSUE TITLE
question about 315MHZ compatibility 

### ISSUE THREAD

**Issue by josephshepin** [wagiminator/ATtiny13-TinyRemoteRF#1]
I made a very similar (almost identical) board using the SYN115 following the data sheet as you appear to have done, however I made the 315mhz version of the board. After testing my transmitter and receiver using the radiohead library and a pair of arduino unos, I can confirm that they work, however using the code that you wrote for the ATTiny13 doesn't yield any positive results. Would you be aware of any reason that this code would need some modification for the 315mhz version of the circuit? Thanks

**Comment by wagiminator** [comment]
This should actually work regardless of the transmission frequency. Please check whether the code for the transmitter and receiver has been compiled and uploaded correctly and whether the fuses are set correctly on the ATtiny13. In addition, the timing settings mentioned should be identical in the source codes.

**Comment by josephshepin** [comment]
Ok, thanks for the advice. For uploading the code, I used the Arduino ide and an Arduino uno as an ISP. I'm reasonably sure that my code compiled correctly because adding the led to flash when sending a code does flash. Since I'm using the four button version of the code, It looks like I don't need the fuses, right? Last thing to try would be calibrating timing, maybe getting the usbasp device and trying the makerfile approach for uploading the code.

**Comment by wagiminator** [comment]
It is only important that if the code is compiled for a clock speed of 1.2MHz, then the ATtiny13's fuses are also set to run at 1.2MHz. Otherwise the timing is wrong. But I don't think that the ATtiny's internal oscillator needs to be additionally calibrated.
